spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.application.name=ProjetoDalia
spring.data.mongodb.uri=mongodb+srv://AnaBeatriz:YyxZd5W8EdzNyGHt@dalia10.bmanska.mongodb.net/dalia10?retryWrites=true&w=majority&appName=Dalia10
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=playy.story22@gmail.com
spring.mail.password=ywum tdqu vkts rhqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


