spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.application.name=ProjetoDalia
spring.data.mongodb.uri=mongodb+srv://AnaBeatriz:YyxZd5W8EdzNyGHt@dalia10.bmanska.mongodb.net/dalia10?retryWrites=true&w=majority&appName=Dalia10
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
server.address=0.0.0.0
server.port=${PORT:8080}
brevo.api.key=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
brevo.sender.email=analed988@gmail.com
brevo.sender.name=Dalia
logging.level.org.springframework.security=DEBUG