spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.application.name=ProjetoDalia
spring.data.mongodb.uri=${MONGO_URL}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
server.address=0.0.0.0
server.port=${PORT:8080}
brevo.api.key=${API_KEY}
brevo.sender.email=${EMAIL_API}
brevo.sender.name=Dalia
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.security=DEBUG